# # Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 3000


# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = " " # The "success_symbol" segment is being set to "âœ" with the color "bold green i.e. [âœ](bold green)"
error_symbol = "[âœ–](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
format = '\[AWS: [$profile/($region)]($style)\]'
symbol = "â›… "
style = 'bold white'
disabled = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"
disabled = false

[[battery.display]]
threshold = 30
style = "bold red"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"
disabled = true

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
truncation_symbol = "â€¦/"
home_symbol = " ğŸ "
disabled =  false

[docker_context]
format = 'via [ğŸ³ $context](blue bold)'
disabled = true

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "ï„“ î‚  "
style = "bold purple"

[git_commit]
commit_hash_length = 8
style = "bold purple"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count} "
behind = "ğŸ¢ Ã—${count} "
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count} "
untracked = "ğŸ›¤ï¸  Ã—${count} "
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count} "
staged = "ğŸ—ƒï¸  Ã—${count} "
renamed = "ğŸ“› Ã—${count} "
deleted = "ğŸ—‘ï¸  Ã—${count} "
style = "bright-purple "
format = "$all_status$ahead_behind "

[golang]
format = "[$symbol($version )]($style)"
symbol = "ğŸ¹ "
disabled = false

[gcloud]
format = 'GCP: [$symbol$active$account(@$domain)(\($project\))]($style) '
symbol = "ğŸ”­ "
style = "bold yellow"
disabled = true

[hostname]
ssh_only = true
ssh_symbol = "ğŸŒ "
format = "<[$hostname]($style)> "
trim_at = "-"
style = "bold dimmed white"
disabled = false

[kubernetes]
#format = '[â›µ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
format = '[$symbol$context( \($namespace\) )]($style)'
symbol = "â›µ "
detect_folders = ["!~/"]
detect_files = ["config_k3s"]
disabled = false
# [kubernetes.context_aliases]
# "arn:aws:eks:us-east-1:0123456789:cluster/qa-us-east-1-cse-app" = "QA"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
symbol = "ğŸ‘ "
threshold = 90
style = "bold dimmed white"
disabled = false

[python]
# format = "[$symbol$version]($style) "
# format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
format = '[${symbol}(${version} )]($style)'
style = "bold green"
symbol = "ğŸ "
python_binary = ['python']
pyenv_prefix = "pyenv-"
disabled = false
pyenv_version_name = true

[ruby]
format = "[$symbol($version )]($style)"
symbol= "ğŸ’ "
detect_extensions = ["rb"]
detect_files = ["Gemfile", ".ruby-version"]
detect_variables = []
disabled = false

[rust]
format = "[$symbol$version]($style) "
style = "bold green"
disabled = false

[terraform]
format = '[ğŸğŸ’¨ tf-$version $workspace]($style) '

[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = true

[username]
style_user = "bold dimmed blue"
show_always = true

[nodejs]
format = "via [ğŸ¤– $version](bold green) "
disabled = false

[vagrant]
format = "[ğŸš¶ $version](bold white) "
disabled = true

[status]
style = 'bg:blue'
symbol = 'ğŸ”´ '
success_symbol = 'ğŸŸ¢ SUCCESS'
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = true

[localip]
ssh_only = false
format = '@[$localipv4](bold green) '
disabled = false

[container]
format = '[$symbol \[$name\]]($style) '
disabled = true
